name: Python Test and Merge

on:
  pull_request:
    branches:
      - master

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust this command based on your project

      - name: Run tests
        run: python -m pytest  # Adjust this command based on your project

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: pytest-report.xml  # Adjust this path based on your test result file

      - name: Merge code if tests pass
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Merging pull request $pr_number..."
          gh pr merge $pr_number --merge
